runtime: python310
instance_class: F2
# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 15
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

#entrypoint: python backend.main

runtime_config:
  python_version: 3

# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10
