steps:
- name: 'python:3.10-slim'
  entrypoint: 'bash'
  args: ['-c', 'pip install poetry && poetry export -f requirements.txt --output requirements.txt && pip install -r requirements.txt']


- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
options: 
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'
